Projet-Browser-Game-master/src/Entity/Boss.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BossRepository")
 */
class Boss
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $health;

    /**
     * @ORM\Column(type="integer")
     */
    private $armour;

    /**
     * @ORM\Column(type="integer")
     */
    private $resist_fire;

    /**
     * @ORM\Column(type="integer")
     */
    private $resist_ice;

    /**
     * @ORM\Column(type="integer")
     */
    private $power;

    /**
     * @ORM\Column(type="integer")
     */
    private $power_ice;

    /**
     * @ORM\Column(type="integer")
     */
    private $power_fire;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Game", mappedBy="boss")
     */
    private $games;

    public function __construct()
    {
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getHealth(): ?int
    {
        return $this->health;
    }

    public function setHealth(int $health): self
    {
        $this->health = $health;

        return $this;
    }

    public function getArmour(): ?int
    {
        return $this->armour;
    }

    public function setArmour(int $armour): self
    {
        $this->armour = $armour;

        return $this;
    }

    public function getResistFire(): ?int
    {
        return $this->resist_fire;
    }

    public function setResistFire(int $resist_fire): self
    {
        $this->resist_fire = $resist_fire;

        return $this;
    }

    public function getResistIce(): ?int
    {
        return $this->resist_ice;
    }

    public function setResistIce(int $resist_ice): self
    {
        $this->resist_ice = $resist_ice;

        return $this;
    }

    public function getPower(): ?int
    {
        return $this->power;
    }

    public function setPower(int $power): self
    {
        $this->power = $power;

        return $this;
    }

    public function getPowerIce(): ?int
    {
        return $this->power_ice;
    }

    public function setPowerIce(int $power_ice): self
    {
        $this->power_ice = $power_ice;

        return $this;
    }

    public function getPowerFire(): ?int
    {
        return $this->power_fire;
    }

    public function setPowerFire(int $power_fire): self
    {
        $this->power_fire = $power_fire;

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->setBoss($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->contains($game)) {
            $this->games->removeElement($game);
            // set the owning side to null (unless already changed)
            if ($game->getBoss() === $this) {
                $game->setBoss(null);
            }
        }

        return $this;
    }
}

Projet-Browser-Game-master/src/Form/BossType.php
<?php

namespace App\Form;

use App\Entity\Boss;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class BossType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('health')
            ->add('armour')
            ->add('resist_fire')
            ->add('resist_ice')
            ->add('power')
            ->add('power_ice')
            ->add('power_fire')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Boss::class,
        ]);
    }
}

Projet-Browser-Game-master/src/Controller/BossController.php
<?php

namespace App\Controller;

use App\Entity\Boss;
use App\Form\BossType;
use App\Form\BossNewType;
use App\Repository\BossRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/boss")
 */
class BossController extends AbstractController
{
    /**
     * @Route("/", name="boss_index", methods={"GET"})
     */
    public function index(BossRepository $bossRepository): Response
    {
        return $this->render('boss/index.html.twig', [
            'bosses' => $bossRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="boss_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $boss = new Boss();
        $form = $this->createForm(BossNewType::class, $boss);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($boss);
            $em->flush();

            return $this->redirectToRoute('boss_index');
        }

        return $this->render('boss/new.html.twig', [
            'boss' => $boss,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="boss_show", methods={"GET"})
     */
    public function show(Boss $boss): Response
    {
        return $this->render('boss/show.html.twig', [
            'boss' => $boss,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="boss_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Boss $boss): Response
    {
        $form = $this->createForm(BossType::class, $boss);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('boss_index');
        }

        return $this->render('boss/edit.html.twig', [
            'boss' => $boss,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="boss_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Boss $boss): Response
    {
        if ($this->isCsrfTokenValid('delete'.$boss->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($boss);
            $entityManager->flush();
        }

        return $this->redirectToRoute('boss_index');
    }
}

Projet-Browser-Game-master/templates/boss/_delete_form.html.twig
<form method="post" action="{{ path('boss_delete', {'id': boss.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ boss.id) }}">
    <button class="btn">Delete</button>
</form>

Projet-Browser-Game-master/templates/boss/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Projet-Browser-Game-master/templates/boss/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Boss{% endblock %}

{% block body %}
    <h1>Edit Boss</h1>

    {{ include('boss/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('boss_index') }}">back to list</a>

    {{ include('boss/_delete_form.html.twig') }}
{% endblock %}

Projet-Browser-Game-master/templates/boss/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Boss index{% endblock %}

{% block body %}
    <h1>Boss index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Health</th>
                <th>Armour</th>
                <th>Resist_fire</th>
                <th>Resist_ice</th>
                <th>Power</th>
                <th>Power_ice</th>
                <th>Power_fire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for boss in bosses %}
            <tr>
                <td>{{ boss.id }}</td>
                <td>{{ boss.name }}</td>
                <td>{{ boss.health }}</td>
                <td>{{ boss.armour }}</td>
                <td>{{ boss.resistFire }}</td>
                <td>{{ boss.resistIce }}</td>
                <td>{{ boss.power }}</td>
                <td>{{ boss.powerIce }}</td>
                <td>{{ boss.powerFire }}</td>
                <td>
                    <a href="{{ path('boss_show', {'id': boss.id}) }}">show</a>
                    <a href="{{ path('boss_edit', {'id': boss.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('boss_new') }}">Create new</a>
{% endblock %}

Projet-Browser-Game-master/templates/boss/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Boss{% endblock %}

{% block body %}
    <h1>Create new Boss</h1>

    {{ include('boss/_form.html.twig') }}

    <a href="{{ path('boss_index') }}">back to list</a>
{% endblock %}

Projet-Browser-Game-master/templates/boss/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Boss{% endblock %}

{% block body %}
    <h1>Boss</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ boss.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ boss.name }}</td>
            </tr>
            <tr>
                <th>Health</th>
                <td>{{ boss.health }}</td>
            </tr>
            <tr>
                <th>Armour</th>
                <td>{{ boss.armour }}</td>
            </tr>
            <tr>
                <th>Resist_fire</th>
                <td>{{ boss.resistFire }}</td>
            </tr>
            <tr>
                <th>Resist_ice</th>
                <td>{{ boss.resistIce }}</td>
            </tr>
            <tr>
                <th>Power</th>
                <td>{{ boss.power }}</td>
            </tr>
            <tr>
                <th>Power_ice</th>
                <td>{{ boss.powerIce }}</td>
            </tr>
            <tr>
                <th>Power_fire</th>
                <td>{{ boss.powerFire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('boss_index') }}">back to list</a>

    <a href="{{ path('boss_edit', {'id': boss.id}) }}">edit</a>

    {{ include('boss/_delete_form.html.twig') }}
{% endblock %}