Projet-Browser-Game-master/src/Entity/Stuff.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StuffRepository")
 */
class Stuff
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $m_health;

    /**
     * @ORM\Column(type="integer")
     */
    private $m_armour;

    /**
     * @ORM\Column(type="integer")
     */
    private $m_resist_fire;

    /**
     * @ORM\Column(type="integer")
     */
    private $m_resist_ice;

    /**
     * @ORM\Column(type="integer")
     */
    private $m_power;

    /**
     * @ORM\Column(type="integer")
     */
    private $m_power_ice;

    /**
     * @ORM\Column(type="integer")
     */
    private $m_power_fire;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Slot", inversedBy="stuffs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $slot;

    public function __construct()
    {
        $this->games = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMHealth(): ?int
    {
        return $this->m_health;
    }

    public function setMHealth(int $m_health): self
    {
        $this->m_health = $m_health;

        return $this;
    }

    public function getMArmour(): ?int
    {
        return $this->m_armour;
    }

    public function setMArmour(int $m_armour): self
    {
        $this->m_armour = $m_armour;

        return $this;
    }

    public function getMResistFire(): ?int
    {
        return $this->m_resist_fire;
    }

    public function setMResistFire(int $m_resist_fire): self
    {
        $this->m_resist_fire = $m_resist_fire;

        return $this;
    }

    public function getMResistIce(): ?int
    {
        return $this->m_resist_ice;
    }

    public function setMResistIce(int $m_resist_ice): self
    {
        $this->m_resist_ice = $m_resist_ice;

        return $this;
    }

    public function getMPower(): ?int
    {
        return $this->m_power;
    }

    public function setMPower(int $m_power): self
    {
        $this->m_power = $m_power;

        return $this;
    }

    public function getMPowerIce(): ?int
    {
        return $this->m_power_ice;
    }

    public function setMPowerIce(int $m_power_ice): self
    {
        $this->m_power_ice = $m_power_ice;

        return $this;
    }

    public function getMPowerFire(): ?int
    {
        return $this->m_power_fire;
    }

    public function setMPowerFire(int $m_power_fire): self
    {
        $this->m_power_fire = $m_power_fire;

        return $this;
    }

    public function getSlot(): ?Slot
    {
        return $this->slot;
    }

    public function setSlot(?Slot $slot): self
    {
        $this->slot = $slot;

        return $this;
    }
}

Projet-Browser-Game-master/src/Form/StuffType.php
<?php

namespace App\Form;

use App\Entity\Stuff;
use App\Entity\Slot;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class StuffType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('m_health')
            ->add('m_armour')
            ->add('m_resist_fire')
            ->add('m_resist_ice')
            ->add('m_power')
            ->add('m_power_ice')
            ->add('m_power_fire')
            ->add('slot', EntityType::class,[
                'class' => Slot::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stuff::class,
        ]);
    }
}

Projet-Browser-Game-master/src/Controller/StuffController.php
<?php

namespace App\Controller;

use App\Entity\Stuff;
use App\Entity\Slot;
use App\Form\StuffType;
use App\Form\StuffNewType;
use App\Repository\StuffRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/stuff")
 */
class StuffController extends AbstractController
{
    /**
     * @Route("/", name="stuff_index", methods={"GET"})
     */
    public function index(StuffRepository $stuffRepository): Response
    {
        return $this->render('stuff/index.html.twig', [
            'stuffs' => $stuffRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="stuff_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $stuff = new Stuff();
        $form = $this->createForm(StuffNewType::class, $stuff);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($stuff);
            $entityManager->flush();

            return $this->redirectToRoute('stuff_index');
        }

        return $this->render('stuff/new.html.twig', [
            'stuff' => $stuff,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="stuff_show", methods={"GET"})
     */
    public function show(Stuff $stuff): Response
    {
        return $this->render('stuff/show.html.twig', [
            'stuff' => $stuff,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="stuff_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Stuff $stuff): Response
    {
        dd($stuff);
        
        $form = $this->createForm(StuffType::class, $stuff);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('stuff_index');
        }

        return $this->render('stuff/edit.html.twig', [
            'stuff' => $stuff,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="stuff_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Stuff $stuff): Response
    {
        if ($this->isCsrfTokenValid('delete'.$stuff->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($stuff);
            $entityManager->flush();
        }

        return $this->redirectToRoute('stuff_index');
    }
}

Projet-Browser-Game-master/templates/stuff/_delete_form.html.twig
<form method="post" action="{{ path('stuff_delete', {'id': stuff.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stuff.id) }}">
    <button class="btn">Delete</button>
</form>

Projet-Browser-Game-master/templates/stuff/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Projet-Browser-Game-master/templates/stuff/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Stuff{% endblock %}

{% block body %}
    <h1>Edit Stuff</h1>

    {{ include('stuff/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('stuff_index') }}">back to list</a>

    {{ include('stuff/_delete_form.html.twig') }}
{% endblock %}

Projet-Browser-Game-master/templates/stuff/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stuff index{% endblock %}

{% block body %}
    <h1>Stuff index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>M_health</th>
                <th>M_armour</th>
                <th>M_resist_fire</th>
                <th>M_resist_ice</th>
                <th>M_power</th>
                <th>M_power_ice</th>
                <th>M_power_fire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for stuff in stuffs %}
            <tr>
                <td>{{ stuff.id }}</td>
                <td>{{ stuff.name }}</td>
                <td>{{ stuff.mHealth }}</td>
                <td>{{ stuff.mArmour }}</td>
                <td>{{ stuff.mResistFire }}</td>
                <td>{{ stuff.mResistIce }}</td>
                <td>{{ stuff.mPower }}</td>
                <td>{{ stuff.mPowerIce }}</td>
                <td>{{ stuff.mPowerFire }}</td>
                <td>
                    <a href="{{ path('stuff_show', {'id': stuff.id}) }}">show</a>
                    <a href="{{ path('stuff_edit', {'id': stuff.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('stuff_new') }}">Create new</a>
{% endblock %}

Projet-Browser-Game-master/templates/stuff/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Stuff{% endblock %}

{% block body %}
    <h1>Create new Stuff</h1>

    {{ include('stuff/_form.html.twig') }}

    <a href="{{ path('stuff_index') }}">back to list</a>
{% endblock %}

Projet-Browser-Game-master/templates/stuff/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stuff{% endblock %}

{% block body %}
    <h1>Stuff</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ stuff.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ stuff.name }}</td>
            </tr>
            <tr>
                <th>M_health</th>
                <td>{{ stuff.mHealth }}</td>
            </tr>
            <tr>
                <th>M_armour</th>
                <td>{{ stuff.mArmour }}</td>
            </tr>
            <tr>
                <th>M_resist_fire</th>
                <td>{{ stuff.mResistFire }}</td>
            </tr>
            <tr>
                <th>M_resist_ice</th>
                <td>{{ stuff.mResistIce }}</td>
            </tr>
            <tr>
                <th>M_power</th>
                <td>{{ stuff.mPower }}</td>
            </tr>
            <tr>
                <th>M_power_ice</th>
                <td>{{ stuff.mPowerIce }}</td>
            </tr>
            <tr>
                <th>M_power_fire</th>
                <td>{{ stuff.mPowerFire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('stuff_index') }}">back to list</a>

    <a href="{{ path('stuff_edit', {'id': stuff.id}) }}">edit</a>

    {{ include('stuff/_delete_form.html.twig') }}
{% endblock %}